sudo: false

language: go

go:
  - 1.6

addons:
  postgresql: "9.4"

env: GOARCH=amd64 TEST_HOST=127.0.0.1

install:
  - (mkdir -p $GOPATH/src/upper.io && cd $GOPATH/src/upper.io && git clone https://github.com/upper/db.git db.v2 && cd db.v2 git pull -a && git checkout 185092eb4a45141a7765390d7f39f081cbee4a71 && go build && go install) # temporal fix
  - go get -v -t -d

script:
  - rm -rf $GOPATH/src/upper.io/bond
  - ln -s $GOPATH/src/github.com/upper/bond $GOPATH/src/upper.io/bond
  - cd $GOPATH/src/upper.io/bond
  - make test
