sudo: false

language: go

go:
  - 1.4
  - 1.4.1
  - 1.4.2

addons:
  postgresql: "9.4"

env: GOARCH=amd64 TEST_HOST=127.0.0.1

install:
  - go get -v -t -d
  - (cd $GOPATH/src/upper.io/db && git pull -a && git checkout issue-103 && go build && go install) # temporal fix

script:
  - rm -rf $GOPATH/src/github.com/upper
  - ln -s $GOPATH/src/upper.io/db/bond $GOPATH/src/github.com/upper
  - cd $GOPATH/src/upper.io/db/bond
  - make test
