sudo: false

language: go

go:
  - 1.6

addons:
  postgresql: "9.4"

env: GOARCH=amd64 TEST_HOST=127.0.0.1

install:
  - go get -v -t -d
  - (cd $GOPATH/src/upper.io/db.v2 && git pull -a && git checkout f504838f1d55623f086f16bea9fa48d058468c1b && go build && go install) # temporal fix

script:
  - rm -rf $GOPATH/src/upper.io/bond
  - ln -s $GOPATH/src/github.com/upper/bond $GOPATH/src/upper.io/bond
  - cd $GOPATH/src/upper.io/bond
  - make test
